PBRP: Fixed All issues while using DM-Verity
* Fixed AutoReboot cause partition was not mounting but others were using it
  Error: libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 499 (recovery), pid 450 (recovery)

* Proper Alignment  of Code

* New Flag to Check Either or Patch

Signed-off-by: Mohd Faraz <androiabledroid@gmail.com>